a = 10
b = 5
print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a <= b)
print(a >= b)
coverage = 30
print(coverage >= 30)
print(coverage <= 30)
vaf = 0.7
print(vaf <= 1)
print(vaf != .07)
gene = "BRCA1"
print(gene == "BRCA1")
depth = 50
print(depth >= 100)
basequality = 30
print(basequality <= 20)
readlength = 50
print(readlength >= 50)
GC = 45
print(GC > 40)
alignment = 90
print(alignment >= 80)
