sequence = "atgcgatta"
print("The same Sequence: ", sequence)
print("The Sequence in uppercase: ", sequence.upper())
upper = sequence.upper()
print("The Sequence in lowercase: ", sequence.lower())
print("The count of A in Sequence: ", upper.count("A"))
print("Sequence replaceing T with U: ", upper.replace("T", "U"))
print("The index of 1st G in the Sequence: ", upper.find("G"))
print("The index of 1st C in the sequence: ", upper.find("C"))
print("Reverse of the sequence: ", sequence[ : : -1])
